# Feature Engineering

## Objective

Transform the validated transaction dataset into machine learning-ready feature datasets.

Input:
datasets/master/master_transactions.csv

Outputs:

- expense_features.csv
- forecasting_features.csv
- merchant_features.csv

This notebook performs:

- Feature planning
- Feature creation
- Validation
- Dataset generation

In [1]:
# Importing libraries

import pandas as pd
import numpy as np
from pathlib import Path

In [2]:
PROJECT_ROOT = Path.cwd().parent

DATASET_DIR = PROJECT_ROOT / "data"
MASTER_DIR = DATASET_DIR / "master"
PROCESSED_DIR = DATASET_DIR / "processed"
FEATURE_STORE_DIR = DATASET_DIR / "feature_store"
METADATA_DIR = PROJECT_ROOT / "metadata"

In [3]:
#Loaded the Dataset
master_file = MASTER_DIR / "final_master_transaction.csv"

In [4]:
df = pd.read_csv(master_file)

In [5]:
df.head()

,transaction_id,transaction_date,transaction_time,merchant,description,amount,currency,payment_method,transaction_type,category,city,state,country,day,week,month,weekend,month_end,salary_week,festival_season
0,TXN000001,2018-01-01,09:22:10,Credit Card Bill Payment,Auto Debit Credit Card Bill Payment,4361.84,INR,Auto Debit,Debit,Bills,Bengaluru,Karnataka,India,1,1,1,0,0,1,0
1,TXN000002,2018-01-01,12:33:23,Zepto,UPI/Paytm/Zepto,1226.03,INR,UPI,Debit,Groceries,Bengaluru,Karnataka,India,1,1,1,0,0,1,0
2,TXN000003,2018-01-01,20:17:30,Ace Hardware India,POS Purchase Ace Hardware India,523.73,INR,Credit Card,Debit,Miscellaneous,Bengaluru,Karnataka,India,1,1,1,0,0,1,0
3,TXN000004,2018-01-01,21:33:19,Zepto,UPI/DR/623175732898/Zepto,1290.29,INR,UPI,Debit,Groceries,Indore,Madhya Pradesh,India,1,1,1,0,0,1,0
4,TXN000005,2018-01-02,08:43:33,House Rent Payment,NEFT Rent Payment,44800.94,INR,NEFT,Debit,Rent,Pune,Maharashtra,India,2,1,1,0,0,1,0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7000 entries, 0 to 6999
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    7000 non-null   object
 1   transaction_date  7000 non-null   object
 2   transaction_time  7000 non-null   object
 3   merchant          7000 non-null   object
 4   description       7000 non-null   object
 5   amount            7000 non-null   float64
 6   currency          7000 non-null   object
 7   payment_method    7000 non-null   object
 8   transaction_type  7000 non-null   object
 9   category          7000 non-null   object
 10  city              7000 non-null   object
 11  state             7000 non-null   object
 12  country           7000 non-null   object
 13  day               7000 non-null   int64
 14  week              7000 non-null   int64
 15  month             7000 non-null   int64
 16  weekend           7000 non-null   int64
 17  month_end         7000 non-null   int64
 18  salary_week       7000 non-null   int64
 19  festival_season   7000 non-null   int64
dtypes: float64(1), int64(7), object(12)
memory usage: 1.1+ MB

In [7]:
df.dtypes

transaction_id       object
transaction_date     object
transaction_time     object
merchant             object
description          object
amount              float64
currency             object
payment_method       object
transaction_type     object
category             object
city                 object
state                object
country              object
day                   int64
week                  int64
month                 int64
weekend               int64
month_end             int64
salary_week           int64
festival_season       int64
dtype: object

In [8]:
df["transaction_date"] = pd.to_datetime(df["transaction_date"])

In [9]:
df["transaction_time"] = pd.to_datetime(df["transaction_time"], format='%H:%M:%S')

In [10]:
df.dtypes

transaction_id              object
transaction_date    datetime64[ns]
transaction_time    datetime64[ns]
merchant                    object
description                 object
amount                     float64
currency                    object
payment_method              object
transaction_type            object
category                    object
city                        object
state                       object
country                     object
day                          int64
week                         int64
month                        int64
weekend                      int64
month_end                    int64
salary_week                  int64
festival_season              int64
dtype: object

In [11]:
df.shape

(7000, 20)

In [12]:
# Verify Required Columns

required_columns = [
    "transaction_date",
    "merchant",
    "description",
    "amount",
    "payment_method",
    "transaction_type",
    "category"
]

missing = [col for col in required_columns if col not in df.columns]

if missing:
    print("Missing columns:", missing)
else:
    print("All required columns are available.")

All required columns are available.

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7000 entries, 0 to 6999
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    7000 non-null   object
 1   transaction_date  7000 non-null   datetime64[ns]
 2   transaction_time  7000 non-null   datetime64[ns]
 3   merchant          7000 non-null   object
 4   description       7000 non-null   object
 5   amount            7000 non-null   float64
 6   currency          7000 non-null   object
 7   payment_method    7000 non-null   object
 8   transaction_type  7000 non-null   object
 9   category          7000 non-null   object
 10  city              7000 non-null   object
 11  state             7000 non-null   object
 12  country           7000 non-null   object
 13  day               7000 non-null   int64
 14  week              7000 non-null   int64
 15  month             7000 non-null   int64
 16  weekend           7000 non-null   int64
 17  month_end         7000 non-null   int64
 18  salary_week       7000 non-null   int64
 19  festival_season   7000 non-null   int64
dtypes: datetime64[ns](2), float64(1), int64(7), object(10)
memory usage: 1.1+ MB

In [14]:
df.shape

(7000, 20)

In [15]:
df.columns

Index(['transaction_id', 'transaction_date', 'transaction_time', 'merchant',
       'description', 'amount', 'currency', 'payment_method',
       'transaction_type', 'category', 'city', 'state', 'country', 'day',
       'week', 'month', 'weekend', 'month_end', 'salary_week',
       'festival_season'],
      dtype='object')

In [16]:
df.columns.tolist()

['transaction_id',
 'transaction_date',
 'transaction_time',
 'merchant',
 'description',
 'amount',
 'currency',
 'payment_method',
 'transaction_type',
 'category',
 'city',
 'state',
 'country',
 'day',
 'week',
 'month',
 'weekend',
 'month_end',
 'salary_week',
 'festival_season']

In [17]:
feature_plan = pd.DataFrame({
    "Column": df.columns,
    "Type": [
        "Identifier",
        "Datetime",
        "Datetime",
        "Text",
        "Text",
        "Numeric",
        "Categorical",
        "Categorical",
        "Categorical",
        "Target",
        "Categorical",
        "Categorical",
        "Categorical",
        "Numeric",
        "Numeric",
        "Numeric",
        "Binary",
        "Binary",
        "Binary",
        "Binary"
    ]
})

feature_plan

              Column         Type
0     transaction_id   Identifier
1   transaction_date     Datetime
2   transaction_time     Datetime
3           merchant         Text
4        description         Text
5             amount      Numeric
6           currency  Categorical
7     payment_method  Categorical
8   transaction_type  Categorical
9           category       Target
10              city  Categorical
11             state  Categorical
12           country  Categorical
13               day      Numeric
14              week      Numeric
15             month      Numeric
16           weekend       Binary
17         month_end       Binary
18       salary_week       Binary
19   festival_season       Binary

In [18]:
feature_usage = pd.DataFrame({
    "Feature": [
        "merchant",
        "description",
        "amount",
        "payment_method",
        "transaction_type",
        "day",
        "week",
        "month",
        "weekend",
        "month_end",
        "salary_week",
        "festival_season"
    ],

    "Expense_Model": [
        "Yes","Yes","Yes","Yes","Yes",
        "No","No","No","No","No","No","No"
    ],

    "Forecast_Model": [
        "No","No","Yes","No","No",
        "Yes","Yes","Yes","Yes","Yes","Yes","Yes"
    ],

    "Merchant_Analytics": [
        "Yes","No","Yes","No","No",
        "No","No","No","No","No","No","No"
    ]
})

feature_usage

             Feature Expense_Model Forecast_Model Merchant_Analytics
0           merchant           Yes             No                Yes
1        description           Yes             No                 No
2             amount           Yes            Yes                Yes
3     payment_method           Yes             No                 No
4   transaction_type           Yes             No                 No
5                day            No            Yes                 No
6               week            No            Yes                 No
7              month            No            Yes                 No
8            weekend            No            Yes                 No
9          month_end            No            Yes                 No
10       salary_week            No            Yes                 No
11   festival_season            No            Yes                 No

In [19]:
df.nunique()

transaction_id      7000
transaction_date     653
transaction_time    6655
merchant              99
description         1176
amount              6587
currency               1
payment_method         8
transaction_type       2
category              13
city                  15
state                 11
country                1
day                   31
week                  52
month                 12
weekend                2
month_end              2
salary_week            2
festival_season        2
dtype: int64

In [20]:
categorical_cols = [
    "currency",
    "payment_method",
    "transaction_type",
    "category",
    "city",
    "state",
    "country"
]

for col in categorical_cols:
    print(f"\n{col}")
    print(df[col].value_counts())

currency
currency
INR    7000
Name: count, dtype: int64

payment_method
payment_method
UPI                2607
Auto Debit         1333
Debit Card         1053
Net Banking         816
Credit Card         697
NEFT                307
Cash Withdrawal      95
IMPS                 92
Name: count, dtype: int64

transaction_type
transaction_type
Debit     6810
Credit     190
Name: count, dtype: int64

category
category
Bills            2059
Food             1328
Groceries         912
Shopping          550
Other             435
Fuel              423
Miscellaneous     358
Subscription      242
Salary            173
Entertainment     167
Rent              165
Insurance         152
Investment         36
Name: count, dtype: int64

city
city
Bengaluru    1015
Indore        452
Nagpur        450
Pune          447
Noida         444
Mumbai        434
Delhi         432
Kochi         432
Hyderabad     431
Chennai       431
Jaipur        431
Lucknow       422
Surat         410
Kolkata       391
Ahmedabad     378
Name: count, dtype: int64

state
state
Maharashtra       1331
Karnataka         1015
Uttar Pradesh      866
Gujarat            788
Madhya Pradesh     452
Kerala             432
Delhi              432
Rajasthan          431
Tamil Nadu         431
Telangana          431
West Bengal        391
Name: count, dtype: int64

country
country
India    7000
Name: count, dtype: int64

In [21]:
status = [
    "Excluded",   # transaction_id
    "Selected",   # transaction_date
    "Future",     # transaction_time
    "Selected",   # merchant
    "Selected",   # description
    "Selected",   # amount
    "Excluded",   # currency
    "Selected",   # payment_method
    "Selected",   # transaction_type
    "Target",     # category
    "Future",     # city
    "Future",     # state
    "Excluded",   # country
    "Selected",   # day
    "Selected",   # week
    "Selected",   # month
    "Selected",   # weekend
    "Selected",   # month_end
    "Selected",   # salary_week
    "Selected"    # festival_season
]

reason = [
    "Unique transaction identifier; not useful for prediction.",
    "Required for chronological ordering and forecasting.",
    "Reserved for future hour-of-day and time-based features.",
    "Strong indicator of transaction category and merchant analytics.",
    "Provides transaction context for NLP-based classification.",
    "Core numerical feature used across multiple models.",
    "Constant value (INR); provides no predictive information.",
    "Useful categorical feature indicating payment channel.",
    "Distinguishes debit and credit transactions.",
    "Prediction target for expense classification; category label for analytics.",
    "Useful for future regional spending analysis and visualization.",
    "Useful for future regional spending analysis and visualization.",
    "Constant value (India); provides no predictive information.",
    "Captures day-of-month spending patterns.",
    "Captures weekly spending patterns.",
    "Captures monthly spending trends.",
    "Captures weekday vs weekend spending behaviour.",
    "Captures month-end spending behaviour.",
    "Captures salary-cycle spending behaviour.",
    "Captures seasonal/festival spending behaviour."
]

feature_plan["Status"] = status
feature_plan["Reason"] = reason

In [22]:
feature_plan

,Column,Type,Status,Reason
0,transaction_id,Identifier,Excluded,Unique transaction identifier; not useful for ...
1,transaction_date,Datetime,Selected,Required for chronological ordering and foreca...
2,transaction_time,Datetime,Future,Reserved for future hour-of-day and time-based...
3,merchant,Text,Selected,Strong indicator of transaction category and m...
4,description,Text,Selected,Provides transaction context for NLP-based cla...
5,amount,Numeric,Selected,Core numerical feature used across multiple mo...
6,currency,Categorical,Excluded,Constant value (INR); provides no predictive i...
7,payment_method,Categorical,Selected,Useful categorical feature indicating payment ...
8,transaction_type,Categorical,Selected,Distinguishes debit and credit transactions.
9,category,Target,Target,Prediction target for expense classification; ...
10,city,Categorical,Future,Useful for future regional spending analysis a...
11,state,Categorical,Future,Useful for future regional spending analysis a...
12,country,Categorical,Excluded,Constant value (India); provides no predictive...
13,day,Numeric,Selected,Captures day-of-month spending patterns.
14,week,Numeric,Selected,Captures weekly spending patterns.
15,month,Numeric,Selected,Captures monthly spending trends.
16,weekend,Binary,Selected,Captures weekday vs weekend spending behaviour.
17,month_end,Binary,Selected,Captures month-end spending behaviour.
18,salary_week,Binary,Selected,Captures salary-cycle spending behaviour.
19,festival_season,Binary,Selected,Captures seasonal/festival spending behaviour.