In [22]:
import pandas as pd

df = pd.read_csv("D:/clg_project/AI-Financial-Wellness-Coach/data/raw/Customer_financial_profiles.csv")

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 21 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 20000 non-null  int64
 1   current_age        20000 non-null  int64
 2   birth_year         20000 non-null  int64
 3   birth_month        20000 non-null  int64
 4   gender             20000 non-null  object
 5   address            20000 non-null  object
 6   per_capita_income  20000 non-null  int64
 7   yearly_income      20000 non-null  int64
 8   total_debt         20000 non-null  int64
 9   credit_score       20000 non-null  int64
 10  num_credit_cards   20000 non-null  int64
 11  transaction_id     20000 non-null  int64
 12  date               20000 non-null  object
 13  client_id          20000 non-null  object
 14  card_id            20000 non-null  object
 15  amount             20000 non-null  float64
 16  use_chip           20000 non-null  object
 17  merchant_id        20000 non-null  object
 18  merchant_city      20000 non-null  object
 19  merchant_state     20000 non-null  object
 20  zip                20000 non-null  int64
dtypes: float64(1), int64(11), object(9)
memory usage: 3.2+ MB

In [24]:
df.columns

Index(['id', 'current_age', 'birth_year', 'birth_month', 'gender', 'address',
       'per_capita_income', 'yearly_income', 'total_debt', 'credit_score',
       'num_credit_cards', 'transaction_id', 'date', 'client_id', 'card_id',
       'amount', 'use_chip', 'merchant_id', 'merchant_city', 'merchant_state',
       'zip'],
      dtype='object')

In [25]:
df1 = df[["transaction_id","current_age","yearly_income","credit_score","date","amount","merchant_id","merchant_city"
,"id"]]

In [26]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   transaction_id  20000 non-null  int64
 1   current_age     20000 non-null  int64
 2   yearly_income   20000 non-null  int64
 3   credit_score    20000 non-null  int64
 4   date            20000 non-null  object
 5   amount          20000 non-null  float64
 6   merchant_id     20000 non-null  object
 7   merchant_city   20000 non-null  object
 8   id              20000 non-null  int64
dtypes: float64(1), int64(5), object(3)
memory usage: 1.4+ MB

In [31]:
df1 =df1.copy()

In [ ]:
df1.rename(columns = {
    "id":"customer_id", "current_age" :"age", "yearly_income": "income"},inplace=True)

In [28]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   transaction_id  20000 non-null  int64
 1   age             20000 non-null  int64
 2   income          20000 non-null  int64
 3   credit_score    20000 non-null  int64
 4   date            20000 non-null  object
 5   amount          20000 non-null  float64
 6   merchant_id     20000 non-null  object
 7   merchant_city   20000 non-null  object
 8   customer_id     20000 non-null  int64
dtypes: float64(1), int64(5), object(3)
memory usage: 1.4+ MB

In [37]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   transaction_id  20000 non-null  int64
 1   age             20000 non-null  int64
 2   income          20000 non-null  int64
 3   credit_score    20000 non-null  int64
 4   date            20000 non-null  datetime64[ns]
 5   amount          20000 non-null  float64
 6   merchant_id     20000 non-null  object
 7   merchant_city   20000 non-null  object
 8   customer_id     20000 non-null  int64
dtypes: datetime64[ns](1), float64(1), int64(5), object(2)
memory usage: 1.4+ MB

In [35]:
df1.head()

,transaction_id,age,income,credit_score,date,amount,merchant_id,merchant_city,customer_id
0,1251,64,1033501,715,2024-03-28,1483.94,MCH00496,Mumbai,1
1,9976,39,820965,834,2025-09-20,1274.72,MCH00374,Mumbai,2
2,6084,50,271138,609,2024-10-02,7622.04,MCH00108,Kolkata,3
3,3350,27,289898,782,2023-09-02,3970.48,MCH00001,Indore,4
4,11725,45,545697,608,2025-05-25,418.45,MCH00254,Bengaluru,5

In [36]:
df1['date']=pd.to_datetime(df1['date'])

In [39]:
df1.shape

(20000, 9)

In [45]:
df1.sample(10)

,transaction_id,age,income,credit_score,date,amount,merchant_id,merchant_city,customer_id
16260,16689,59,492645,790,2024-07-13,2492.86,MCH00319,Lucknow,16261
7242,17988,47,483961,627,2024-09-04,3901.67,MCH00453,Nagpur,7243
10012,13660,67,449356,752,2024-01-28,2523.11,MCH00274,Indore,10013
6713,17492,34,655502,693,2024-12-21,3617.31,MCH00272,Nagpur,6714
13128,2914,68,511103,773,2023-12-15,1727.95,MCH00072,Bhopal,13129
13905,16676,61,661481,593,2025-08-27,7461.43,MCH00446,Patna,13906
3627,19216,62,267737,678,2025-01-29,3691.27,MCH00236,Surat,3628
18999,1266,26,292498,682,2024-03-31,1289.48,MCH00021,Chennai,19000
4001,7590,53,372596,810,2025-07-16,2541.05,MCH00053,Chennai,4002
16366,9290,30,878113,825,2025-06-02,2207.27,MCH00112,Patna,16367

In [46]:
df1.merchant_city.unique()

array(['Mumbai', 'Kolkata', 'Indore', 'Bengaluru', 'Chennai', 'Surat',
       'Bhopal', 'Lucknow', 'Pune', 'Jaipur', 'Ahmedabad', 'Delhi',
       'Nagpur', 'Patna', 'Hyderabad'], dtype=object)

In [48]:
df1.to_csv("D:/clg_project/AI-Financial-Wellness-Coach/data/processed/Customer_financial_cleaned.csv",index=False)