In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('D:/clg_project/AI-Financial-Wellness-Coach/data/raw/main_data/Personal_Finance_Dataset (1).csv')

In [3]:
df.head()

,Date,Transaction Description,Category,Amount,Type
0,2020-01-02,Score each.,Food & Drink,1485.69,Expense
1,2020-01-02,Quality throughout.,Utilities,1475.58,Expense
2,2020-01-04,Instead ahead despite measure ago.,Rent,1185.08,Expense
3,2020-01-05,Information last everything thank serve.,Investment,2291.00,Income
4,2020-01-13,Future choice whatever from.,Food & Drink,1126.88,Expense

In [4]:
df.shape

(1500, 5)

In [5]:
df.columns

Index(['Date', 'Transaction Description', 'Category', 'Amount', 'Type'], dtype='str')

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 5 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Date                     1500 non-null   str
 1   Transaction Description  1500 non-null   str
 2   Category                 1500 non-null   str
 3   Amount                   1500 non-null   float64
 4   Type                     1500 non-null   str
dtypes: float64(1), str(4)
memory usage: 58.7 KB

In [7]:
df.describe()

            Amount
count  1500.000000
mean   1307.520913
std     982.283361
min      14.370000
25%     629.340000
50%    1156.285000
75%    1712.932500
max    4996.000000

In [8]:
df.describe(include="object")

C:\Users\hp\AppData\Local\Temp\ipykernel_1924\702825166.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include="object")

              Date Transaction Description Category     Type
count         1500                    1500     1500     1500
unique        1025                    1500       10        2
top     2023-01-24             Score each.     Rent  Expense
freq             6                       1      165     1222

In [9]:
df.describe(include="object")

C:\Users\hp\AppData\Local\Temp\ipykernel_1924\702825166.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include="object")

              Date Transaction Description Category     Type
count         1500                    1500     1500     1500
unique        1025                    1500       10        2
top     2023-01-24             Score each.     Rent  Expense
freq             6                       1      165     1222

In [10]:
df.duplicated().sum()

np.int64(0)